# hostname (and path) to the root eg. http://spf13.com/
baseURL = "https://jastdogit.github.io/"

# Language
# languageCode = "en-us"

# Site title
title = "Hi, I'm Franky."

# Copyright
# copyright = "(c) 2019 franky."

# Theme to use (located in /themes/THEMENAME/)
theme = "tale"

name = "Tale"
license = "MIT"
licenselink = "https://github.com/EmielH/tale-hugo/blob/master/LICENSE"
description = "A port of the Tale theme for Hugo. Tale is a minimal Jekyll theme curated for storytellers."
homepage = "https://github.com/EmielH/tale-hugo"
tags = ["minimal", "clean", "responsive", "simple", "personal", "blog", "starter", "light", "typography"]
features = ["pagination"]
min_version = "0.50"

[author]
	name = "Emiel Hollander"
	homepage = "https://www.emielhollander.nl"

# If porting an existing theme
[original]
	name = "Chester How"
	homepage = "https://github.com/chesterhow/tale"
	repo = "https://github.com/chesterhow/tale"
